# Generated by Django 2.0.6 on 2018-08-22 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('fav_cuisine', models.CharField(blank=True, choices=[('American', 'American'), ('Asian', 'Asian'), ('Italian', 'Italian'), ('Still tasting!', 'Still tasting!')], default='American', max_length=20)),
                ('dining_pref', models.CharField(blank=True, choices=[('Once a week', 'Once a week'), ('Couple times a week', 'Couple times a week'), ('Once a month', 'Once a month'), ('Couple times a month', 'Couple times a month'), ('Still deciding!', 'Still deciding!')], default='Once a month', max_length=25)),
                ('ambience', models.CharField(blank=True, choices=[('Bustling', 'Bustling'), ('Calm', 'Calm'), ('Gastro-pub feel', 'Gastro-pub feel'), ('Fine Dining', 'Fine Dining'), ('Casual', 'Casual'), ('Still deciding!', 'Still deciding!')], default='Calm', max_length=25)),
                ('unfav_cuisine', models.CharField(blank=True, choices=[('American', 'American'), ('Asian', 'Asian'), ('Italian', 'Italian'), ('Still tasting!', 'Still tasting!')], default='American', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
