# Generated by Django 2.0.7 on 2018-08-01 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='profile_image')),
                ('fav_cuisine', models.CharField(blank=True, choices=[('american', 'American'), ('asian', 'Asian'), ('italian', 'Italian'), (None, 'Still tasting!')], default='american', max_length=20)),
                ('dining_pref', models.CharField(blank=True, choices=[('weekly', 'Once a week'), ('multi_weekly', 'Couple times a week'), ('monthly', 'Once a month'), ('multi_monthly', 'Couple times a month'), (None, 'Still deciding!')], default='monthly', max_length=25)),
                ('ambience', models.CharField(blank=True, choices=[('bustling', 'Bustling'), ('calm', 'Calm'), ('gastro', 'Gastro-pub feel'), ('fine_dining', 'Fine Dining'), ('casual', 'Casual'), (None, 'Still deciding!')], default='calm', max_length=25)),
                ('unfav_cuisine', models.CharField(blank=True, choices=[('american', 'American'), ('asian', 'Asian'), ('italian', 'Italian'), (None, 'Still tasting!')], default='american', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
