# Generated by Django 2.0.4 on 2018-06-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0004_auto_20180627_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribe',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
