# Generated by Django 2.0.7 on 2018-07-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribes', '0007_auto_20180716_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('datetime',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
